Repository depromeet/bbo-gak-client, pull requests merged in 2024-08, with the labels that each got.

#24 feat(memo): 메모 UI 구현
  src/app/(sidebar)/write/components/MemoContainer/Memo/Memo.tsx
  src/app/(sidebar)/write/components/MemoContainer/MemoContainer.tsx
  src/app/(sidebar)/write/page.tsx
  src/app/layout.tsx
  src/styles/memo.css
  src/system/components/Icon/Icon.tsx
  src/system/components/Icon/SVG/FilledMemo.tsx
  src/system/components/Icon/SVG/RemoveMemo.tsx
  src/system/components/Icon/SVG/SubmitArrow.tsx
  src/system/components/Textarea/Textarea.tsx
Labels: feature

#27 feat(editor): 에디터 API 연결
  src/app/(sidebar)/write/[id]/api/useDeleteCardTag/useDeleteCardTag.ts
  src/app/(sidebar)/write/[id]/api/useDeleteMemo.ts
  src/app/(sidebar)/write/[id]/api/useGetCardDetail/useGetCardDetail.ts
  src/app/(sidebar)/write/[id]/api/usePostCardTag/usePostCardTag.ts
  src/app/(sidebar)/write/[id]/api/usePostMemo.ts
  src/app/(sidebar)/write/[id]/api/usePutCardContent/usePutCardContent.ts
  src/app/(sidebar)/write/[id]/api/usePutCardTitle/usePutCardTitle.ts
  src/app/(sidebar)/write/[id]/api/usesPutMemo.ts
  src/app/(sidebar)/write/[id]/components/MemoContainer/Memo/Memo.tsx
  src/app/(sidebar)/write/[id]/fetcher/CardTagFetcher.tsx
  src/app/(sidebar)/write/[id]/fetcher/MemosFetcher.tsx
  src/app/(sidebar)/write/[id]/hooks/index.ts
  src/app/(sidebar)/write/[id]/layout.tsx
  src/app/(sidebar)/write/[id]/page.tsx
  src/app/(sidebar)/write/components/MemoContainer/Memo/Memo.tsx
  src/app/(sidebar)/write/components/MemoContainer/MemoContainer.tsx
  src/app/(sidebar)/write/page.tsx
  src/app/layout.tsx
  src/components/Editor/Editor.tsx
  src/components/Editor/EditorProvider/EditorProvider.tsx
  src/components/Editor/useEditor.ts
  src/hooks/useCallbackOnce.ts
  src/lib/SSRSafeSuspense/SSRSafeSuspense.tsx
Labels: feature

#30 feat(editor): memo 구현
  src/app/(sidebar)/write/[id]/api/useGetCardDetail/useGetCardDetail.ts
  src/app/(sidebar)/write/[id]/api/useGetTags/useGetTags.ts
  src/app/(sidebar)/write/[id]/fetcher/TagsFetcher.tsx
  src/app/(sidebar)/write/[id]/hooks/index.ts
  src/app/(sidebar)/write/[id]/layout.tsx
  src/lib/QueryProvider/QueryProvider.tsx
Labels: feature

#41 feat: 내 정보 페이지 스크롤 케이스 & 스켈레톤 구현
  src/app/(sidebar)/(my-info)/apis/useGetInfoCardList.ts
  src/app/(sidebar)/(my-info)/apis/usePostCard.ts
  src/app/(sidebar)/(my-info)/components/InfoCardList.tsx
  src/app/(sidebar)/(my-info)/components/InfoCardSkeleton.tsx
  src/app/(sidebar)/(my-info)/page.tsx
  src/app/(sidebar)/my-recruit/page.tsx
  src/components/InfoCard.tsx
  src/system/components/Icon/SVG/Add.tsx
Labels: UI

#44 feat: 개별창 띄우기
  src/app/(sidebar)/(my-info)/apis/useGetCardTags.ts
  src/app/(sidebar)/(my-info)/components/InfoCardSkeleton.tsx
  src/app/(sidebar)/layout.tsx
  src/app/(sidebar)/my-recruit/[id]/mocks.ts
  src/app/(sidebar)/write/[id]/page.tsx
  src/components/CardWindow/CardWindow.tsx
  src/components/CardWindow/context.tsx
  src/components/InfoCard.tsx
  src/hooks/apis/useGetInfoCardDetail.ts
  src/system/components/Icon/Icon.tsx
  src/system/components/Icon/SVG/FullScreenCorner.tsx
  src/system/components/Icon/SVG/ToLeft.tsx
  src/system/components/Tag/Tag.tsx
Labels: feature

#54 feat(card): 글작성(카드) QA 해결
  src/app/(sidebar)/(my-info)/components/AddInfoCardDialog.tsx
  src/app/(sidebar)/write/[id]/api/useDeleteCardTag/useDeleteCardTag.ts
  src/app/(sidebar)/write/[id]/api/useDeleteMemo.ts
  src/app/(sidebar)/write/[id]/api/useGetCardDetail/useGetCardDetail.ts
  src/app/(sidebar)/write/[id]/api/usePostCardTag/usePostCardTag.ts
  src/app/(sidebar)/write/[id]/api/usePutCardTitle/usePutCardTitle.ts
  src/app/(sidebar)/write/[id]/api/usePutCardType/usePutCardType.ts
  src/app/(sidebar)/write/[id]/api/usesPutMemo.ts
  src/app/(sidebar)/write/[id]/components/MemoContainer/Memo/DeleteMemoDialog.tsx
  src/app/(sidebar)/write/[id]/components/MemoContainer/Memo/Memo.tsx
  src/app/(sidebar)/write/[id]/components/MemoContainer/MemoContainer.tsx
  src/app/(sidebar)/write/[id]/hooks/index.ts
  src/app/(sidebar)/write/[id]/page.tsx
  src/components/Editor/Editor.tsx
  src/system/components/Icon/Icon.tsx
  src/types/info.ts
Labels: bug, refactor

#55 fix(editor): 에디터 QA 구현
  src/components/Editor/extensions/TextMenu/ContentTypePicker.tsx
  src/components/Editor/extensions/TextMenu/TextMenu.tsx
  src/components/Editor/extensions/menu/FontFamilyPicker.tsx
  src/components/Editor/extensions/menu/FontSizePicker.tsx
Labels: bug, refactor

#57 feat(editor): 이미지 업로드 API 구현
  src/apis/image.ts
  src/components/Editor/extensions/ImageBlock/ImageBlockMenu.tsx
  src/components/Editor/extensions/ImageUpload/view/hooks.ts
  src/components/Editor/extensions/SlashCommand/SlashCommand.ts
  src/components/Editor/useEditor.ts
Labels: feature

#58 fix(qa) QA에서 발견된 오류 수정
  src/app/(sidebar)/layout.tsx
  src/app/(sidebar)/write/[id]/api/useGetCardDetail/useGetCardDetail.ts
  src/app/(sidebar)/write/[id]/api/usePostMemo.ts
  src/app/(sidebar)/write/[id]/components/MemoContainer/Memo/DeleteMemoDialog.tsx
  src/app/(sidebar)/write/[id]/components/MemoContainer/Memo/Memo.tsx
  src/app/(sidebar)/write/[id]/fetcher/CardTagFetcher.tsx
  src/app/(sidebar)/write/[id]/hooks/index.ts
  src/app/(sidebar)/write/[id]/page.tsx
  src/app/AuthRedirect.tsx
  src/app/layout.tsx
  src/app/login/layout.tsx
  src/app/login/page.tsx
  src/components/Editor/useEditor.ts
  src/lib/GoogleProvider.tsx
  src/system/components/Icon/Icon.tsx
  src/system/components/Icon/SVG/AnnouncementFolder.tsx
Labels: bug

#68 fix(memo): 메모 API 수정
  src/app/(sidebar)/write/[id]/api/usePostMemo.ts
  src/app/(sidebar)/write/[id]/components/MemoContainer/Memo/DeleteMemoDialog.tsx
  src/app/(sidebar)/write/[id]/components/MemoContainer/Memo/Memo.tsx
  src/app/(sidebar)/write/[id]/components/MemoContainer/MemoContainer.tsx
  src/app/(sidebar)/write/[id]/fetcher/MemosFetcher.tsx
  src/app/opengraph-image.png
Labels: bug
